# Generated by Django 4.2.4 on 2023-09-18 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=300, verbose_name='название'),
        ),
    ]
