# Generated by Django 4.2.4 on 2023-09-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_period_alter_mailingsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.mailingsettings'),
            preserve_default=False,
        ),
    ]
