# Generated by Django 4.2.4 on 2023-09-27 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mailinglog_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='response',
            field=models.TextField(default='No response received yet'),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='send_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('attempted', 'Attempted'), ('success', 'Success'), ('failed', 'Failed')], default='attempted', max_length=20),
        ),
    ]
