# Generated by Django 4.2.4 on 2023-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mailinglog_response_mailinglog_send_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='last_attempt_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailinglog',
            name='last_attempt_status',
            field=models.CharField(choices=[('attempted', 'Attempted'), ('success', 'Success'), ('failed', 'Failed')], default='attempted', max_length=20),
        ),
    ]
